/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzh_web_Model_JniCongest */

#ifndef _Included_com_lzh_web_Model_JniCongest
#define _Included_com_lzh_web_Model_JniCongest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzh_web_Model_JniCongest
 * Method:    Citycongest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lzh_web_Model_JniCongest_Citycongest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
